config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

   root 'home#index'
   get '/about', to: 'home#about'
   get '/quiz', to:  'welcome#quiz'
   resources :users
   get "/login" => "sessions#new"
   resource  :session, only: [:create, :destroy]
   get "/logout" => "sessions#destroy"

end

app/models/question.rb
class Question < ActiveRecord::Base
  serialize :answers,Array
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true
  validates :admin, :inclusion => {:in => [true, false]}

  def is_admin?
    self.admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :current_user, :logged_in?, :authenticate
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

 def index
 end

 def about
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to(user_path(user))
    else
      flash[:error] = "Incorrect username or password."
      redirect_to(login_path)
    end
  end

  def destroy
    log_out!
    redirect_to(login_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate,            except: [:new, :create]
  before_action :load_user,               except: [:index, :new, :create]
  before_action :authorize_admin_only,    only:   :index
  before_action :authorize_user_or_admin, except: [:index, :new, :create]


  def index
    authorize_admin_only
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    redirect_to user_path(@user)
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render(:edit)
    end
  end

  def update_password
    if !@user.authenticate(user_password_params[:old_password])
      @user.errors.add(:old_password, 'must match the current password')
      render(:password)
    elsif user_password_params[:password].blank?
      @user.errors.add(:new_password, 'can\'t be blank!')
      render(:password)
    elsif @user.update(user_password_params.except(:old_password))
      flash[:notice] = "Your password has been updated!"
      redirect_to user_path(@user)
    else
      render(:password)
    end
  end

  def destroy
    if current_user == @user
      @user.destroy
      log_out!
      flash[:notice] = "Thanks for the memories..."
      redirect_to(root_path)
    else # admin is deleting...
      @user.destroy
      redirect_to(users_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :name,
      :password,
      :password_confirmation
    )
  end

  def user_password_params
    @user_password_params ||= params.require(:user).permit(
      :old_password,
      :password,
      :password_confirmation
    )
  end

  def load_user
    @user = User.find_by(id: params[:id])
    redirect_to root_path if !@user
  end

  def authorize_admin_only
    unless current_user.is_admin?
      redirect_to user_path(current_user), :notice => 'Unauthorized action'

    end
  end

  def authorize_user_or_admin
    unless current_user == @user || current_user.is_admin?
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  before_filter :authenticate_user!
  include SessionsHelper
  helper_method :current_user, :logged_in?, :authenticate

 def quiz

 end

protected
  def authenticate_user!
    unless logged_in?
      redirect_to login_path, :flash => { :error => 'You must be signed in to take the quiz' }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def is_admin?
    @current_user.admin
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authenticate
    redirect_to login_path unless logged_in?
  end

  def log_out!
    session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<%= render "shared/header" %>
<% if flash[:notice] %>
    <div class="flash-message <%= notice ? "notice" : ""%><%= alert ? "error" : ""%>">
      <h1><%= flash[:notice] %></h1>
    </div>
<% end %>
<h1>About</h1>
<%= render "shared/footer" %>

app/views/home/index.html.erb
<head>
  <meta charset="utf-8">
  <title>The Quiz</title>
  <%= stylesheet_link_tag "home" %>
</head>
<div id="wrapper">
  <%= render "shared/header" %>
  <div id="content">
    <h1>Welcome to Games by Dewey Banks</h1>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deweygames</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= yield %>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 2015 Dewey Banks</p>
</footer>

app/views/shared/_header.html.erb
<header>


    <ul>
      <% if current_user && current_user.is_admin? %>
      <li><%= link_to 'Users', users_path %></li>
      <li><%= link_to 'Admin', rails_admin.dashboard_path %></li>
      <% end %>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Take Quiz", quiz_path %></li>
      <% if !current_user %>
      <li><%= link_to "Login", login_path %></li>
      <% end %>
      <li><%= link_to "Logout", logout_path %></li>
    </ul>
</header>

app/views/users/_form.html.erb
<div class="users_form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="flash-message">
      <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="field_users_form" class="field2a">
    <p>
      <%= f.label :email %>:
      <%= f.text_field :email, placeholder: 'Email (required)' %><br/>
    </p>
  </div>
  <div id="field" class="field2a">
    <p>
      <%= f.label :name  %>:
      <%= f.text_field :name, placeholder: 'Name (required)' %><br/>
    </p>
  </div>
  <div id="field" class="field2a pull">
    <p>
      <%= f.label :password %>:
      <%= f.password_field :password, placeholder: 'Password (required)' %><br/></p>
    </div>
    <div id="field" class="field2a conf">
      <p><%= f.label :password_confirmation, 'Confirmation' %>:
      <%= f.password_field :password_confirmation, placeholder: 'Confirmation (required)' %><br/></p>
    </div>
</br>
    <div id="field" class="field2a">
    <p><%= f.submit %></p>
  </div>
<% end %>
</div>

app/views/users/create.html.erb
<div id='sign_up'>
<div id="signup_header">Create a New Account</div>
  <div id='sign_up_form'>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'shared/header' %>

<% if flash[:notice] %>
    <div class="flash-message">
      <h1><%= flash[:notice] %></h1>
    </div>
<% end %>
<section>
<h2>User List</h2>
<table id="usersTable">
  <thead>
    <tr class="usersTableTr">
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <!-- <th>Password digest</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

</section>

app/views/users/new.html.erb
<div id='sign_up'>
<div id="signup_header">Create a New Account</div>
  <div id='sign_up_form'>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<% if flash[:notice] %>
    <div class="flash-message">
      <h1><%= flash[:notice] %></h1>
    </div>
<% end %>

<section>

<div class="user">
  <h1><%= @user.name %> </h1>
  <span> <%= @user.email %></span><br><br>
</div>

<button><%= link_to 'Edit', edit_user_path(@user) %></button>
<button><%= link_to "Logout", logout_path %></button>
</section>

app/views/welcome/quiz.html.erb
<head>
  <meta charset="utf-8">
  <title>The Quiz</title>
  <%= stylesheet_link_tag "quiz" %>
</head>


  <div id="wrapper">
    <%= render "shared/header" %>
    <div id="quiz" class="centered grid__col--8">
        <h1>Awesome Quiz</h1>

        <h2 id="question" class="headline-secondary--grouped"></h2>

        <p id="choice0"></p>
        <button id="guess0" class="btn--default">Select Answer</button>

        <p id="choice1"></p>
        <button id="guess1" class="btn--default">Select Answer</button>
    </div>

    <div id="progress">
        <p id="progress">Question x of y</p>
    </div>

    <%= render "shared/footer" %>
</div>
<%= javascript_include_tag "quiz", "question", "quiz_ui", "app" %>